About and license modal
sos-lapsikyla/ylitse-web pull request #135
Opened 2024-10-18 14:29 UTC by olleih

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
About and license modal is added to Ylitse Web. NPM License Checker (https://github.com/davglass/license-checker) is used to get all licenses in JSON-format. License modal shows all projects and libraries used in Ylitse Web. Application info -modal also shows products UI and API versions.

- [Ticket](https://trello.com/c/7bJBx95b/259-about-license-modal)

Fixes # (issue)

Licenses were not listed before.

## Why was the change made?

Users need to be able to see all the libraries and projects and their licenses.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unittest
- [ ] Cypress e2e -tests

# Caveats?

Does this introduce new warnings or are linter rules suppressed? Why? Is only manual testing applicable for this feature? Is there something special that the reviewer should take into account?

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-19 13:04 UTC, rottabonus requested changes
Very nice!
I would like to see small change in the npm-script, but otherwise solid job!

2024-10-19 13:04 UTC, rottabonus commented on src/features/Navigation/InfoDropdown/index.tsx
> +          <Container onClick={() => toggleAbout()}>
mini improvement, we can put
`onClick={toggleAbout}`

2024-10-19 13:14 UTC, rottabonus commented on licenses.json
I would probably add licenses.json to .gitignore. I guess it should be part of the build-process when we deploy a new version.
However it might be ok to have this in repo. It will get outdated very quickly though, but maybe it does not matter.
@idolgov or @pheis   have any opinion on it?

2024-10-19 13:17 UTC, olleih commented on package.json
> +    "licenses": "npm install license-checker --save-dev && npx license-checker --json > licenses.json",
Done! Renamed and updated documentation as well

2024-10-20 17:04 UTC, rottabonus approved these changes
Nice!

2024-10-20 17:08 UTC, merged